#!/bin/bash

source "$(dirname "$0")/lib/policies.sh" 
source "$(dirname "$0")/lib/instances.sh" 
source "$(dirname "$0")/lib/login.sh" 

if [[ "$1" == "login" ]]; then
    shift
    login $* && exit 0 || exit 1
fi

read -r verb resource flags <<< "$@"

case $resource in
    login)
        ;;
    instances|instance)
        case $verb in
            "get")
                if [[ "$resource" == "instances" ]]; then
                    get_instances ${flags[*]}
                else
                    get_instance ${flags[*]}
                fi
                ;;
            "create")
                create_instance ${flags[*]}
                ;;
            "delete")
                delete_instance ${flags[*]}
                ;;
            "top")
                top_instance ${flags[*]}
                ;;
            "log")
                log_instance ${flags[*]}
                ;;
            *)
                echo "Comando desconhecido para instances" >&2
        esac
        ;;
    policies|policy)
        case $verb in
            "list")
                list_policies ${flags[*]}
                ;;
            "create")
                create_policy ${flags[*]}
                ;;
            "update")
                update_policy ${flags[*]}
                ;;
            "delete")
                delete_policy ${flags[*]}
                ;;
            *)
                echo "Comando desconhecido para policies" >&2
        esac
        ;;
    *)
        echo "Comando desconhecido" >&2
        ;;
esac